quarkus.jackson.fail-on-unknown-properties=true
quarkus.management.enabled=false
%prod.quarkus.management.enabled=true
# ---------
# Database - different strategies for dev, test and prod
# ---------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/dummy
quarkus.hibernate-orm.schema-management.strategy=validate
# ---------
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:./.local-db/customers
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true
# ---------
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true
# ---------
%prod.quarkus.datasource.db-kind=${DB_TYPE:postgresql}
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.hibernate-orm.schema-management.strategy=validate

