quarkus.jackson.fail-on-unknown-properties=true
quarkus.management.enabled=true
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:*}
quarkus.http.cors.methods=${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
quarkus.http.cors.headers=${CORS_HEADERS:accept,authorization,content-type}
quarkus.http.cors.exposed-headers=${CORS_EXPOSED_HEADERS:location}
# ---------
# Database - different strategies for dev, test and prod
# ---------
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/dummy
quarkus.hibernate-orm.schema-management.strategy=validate
# ---------
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:./.local-db/customers
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.hibernate-orm.log.sql=true
# ---------
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true
# ---------
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.hibernate-orm.schema-management.strategy=validate
%prod.quarkus.hibernate-orm.log.sql=false

