quarkus.jackson.fail-on-unknown-properties=true
# database configuration (only effective when active)
quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%dev.quarkus.datasource.jdbc.url=jdbc:h2:./.local-db/customers
# Different strategies for dev, test and prod
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%test.quarkus.hibernate-orm.schema-management.strategy=drop-and-create
%prod.quarkus.hibernate-orm.schema-management.strategy=validate
# log SQL only for dev and test
%dev.quarkus.hibernate-orm.log.sql=true
%test.quarkus.hibernate-orm.log.sql=true
